version: '3.4'

services:
  hacktownback:
    image: hacktownback
    container_name: hack-town-back
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5105:5105"
      - "7150:7150" 
    environment:
        ASPNETCORE_ENVIRONMENT: Development
        DATABASE_HOST: hacktowndb.cbu20qgcsbot.eu-north-1.rds.amazonaws.com
        DATABASE_PORT: 5432
        DATABASE_USER: postgres
        DATABASE_PASSWORD: 585662vcxz
        DATABASE_NAME: hacktowndb