# fly.toml app configuration file generated for hacktownback on 2024-12-27T08:13:15+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hacktownback'
primary_region = 'otp'

[build]

[http_service]
  internal_port = 5150
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
